apiVersion: v1
kind: Service
metadata:
  name: myflask-service
spec:
  selector:
    app: myflask
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort